"""interaction timeline fields

Revision ID: 3ff267fb74ce
Revises: 15d465e5bb81
Create Date: 2026-01-28 19:31:04.772093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff267fb74ce'
down_revision: Union[str, Sequence[str], None] = '15d465e5bb81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policy_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('direction', sa.String(length=20), nullable=False))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=4000),
               type_=sa.Text(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_interactions_channel'))
        batch_op.drop_index(batch_op.f('ix_interactions_created_by_user_id'))
        batch_op.create_index(batch_op.f('ix_interactions_policy_id'), ['policy_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_interactions_created_by_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_interactions_policy_id_policies'), 'policies', ['policy_id'], ['id'])
        batch_op.drop_column('created_by_user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_interactions_policy_id_policies'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_interactions_created_by_user_id_users'), 'users', ['created_by_user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_interactions_policy_id'))
        batch_op.create_index(batch_op.f('ix_interactions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_channel'), ['channel'], unique=False)
        batch_op.alter_column('body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=4000),
               nullable=True)
        batch_op.drop_column('direction')
        batch_op.drop_column('policy_id')

    # ### end Alembic commands ###
