"""init

Revision ID: 588f04da4f61
Revises: 
Create Date: 2026-01-26 20:49:38.573751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588f04da4f61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agencies'))
    )
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agencies_name'), ['name'], unique=True)

    op.create_table('ai_rewrite_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('template_name', sa.String(length=80), nullable=True),
    sa.Column('tone', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('base_text', sa.Text(), nullable=False),
    sa.Column('rewritten_text', sa.Text(), nullable=False),
    sa.Column('validation_passed', sa.Boolean(), nullable=False),
    sa.Column('validation_error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_rewrite_logs'))
    )
    with op.batch_alter_table('ai_rewrite_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_rewrite_logs_policy_id'), ['policy_id'], unique=False)

    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_templates'))
    )
    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_templates_name'), ['name'], unique=True)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_customers_agency_id_agencies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_agency_id'), ['agency_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_users_agency_id_agencies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('policy_number', sa.String(length=60), nullable=False),
    sa.Column('carrier', sa.String(length=80), nullable=False),
    sa.Column('product_type', sa.String(length=80), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('old_premium', sa.Float(), nullable=False),
    sa.Column('renewal_premium', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_policies_agency_id_agencies')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_policies_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies'))
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_expiration_date'), ['expiration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_policy_number'), ['policy_number'], unique=False)

    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_interactions_customer_id_customers')),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_interactions_policy_id_policies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactions'))
    )
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interactions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_policy_id'), ['policy_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_tasks_customer_id_customers')),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_tasks_policy_id_policies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_policy_id'), ['policy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_policy_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_customer_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interactions_policy_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_customer_id'))

    op.drop_table('interactions')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_policy_number'))
        batch_op.drop_index(batch_op.f('ix_policies_expiration_date'))
        batch_op.drop_index(batch_op.f('ix_policies_customer_id'))
        batch_op.drop_index(batch_op.f('ix_policies_agency_id'))

    op.drop_table('policies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_agency_id'))

    op.drop_table('users')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_agency_id'))

    op.drop_table('customers')
    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_templates_name'))

    op.drop_table('message_templates')
    with op.batch_alter_table('ai_rewrite_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_rewrite_logs_policy_id'))

    op.drop_table('ai_rewrite_logs')
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agencies_name'))

    op.drop_table('agencies')
    # ### end Alembic commands ###
