"""add task agency_id

Revision ID: cbeb50d6732c
Revises: 3ff267fb74ce
Create Date: 2026-01-28 21:38:38.655387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbeb50d6732c'
down_revision: Union[str, Sequence[str], None] = '3ff267fb74ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agency_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_tasks_agency_id'), ['agency_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_tasks_agency_id_agencies'), 'agencies', ['agency_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_agency_id_agencies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_agency_id'))
        batch_op.drop_column('agency_id')

    # ### end Alembic commands ###
